### ISSUE TITLE
Von Birgit und Prof. Winter absegnen lassen

### ISSUE THREAD

**Issue by ThomasPause** [IMISE/imise-classicthesis#3]

**Comment by ThomasPause** [comment]
Punkte, die noch mit Prof Winter zu klären sind:
- [ ] zusätzlich auf englisch umbauen?
- [ ] Abstrakt vs Zusammenfassung
- [ ] Zeilenlänge (Länge der Arbeit!)
- [ ] Kapitelbeginn auf rechter Seite (erledigt)
- [ ] Literatur vor den Anhang
- [ ] evtl Anpassen der Word-Vorlage

was kommt in den Anhang?: Code, Screenshots usw

**Comment by KonradHoeffner** [comment]
Herr Winter ist einverstanden, Birgit schaut es sich vielleicht später noch einmal an. Die Issue kann geschlossen werden.
